/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Exchange a username and a password for a session token
     * @description Answer a session token, or let the service's refusal become a 401 or a 429.
     *
     *     The username and the password travel to the service exactly as they arrived: normalising them
     *     is a decision, and decisions are not made here. The address is the exception, and it is not a
     *     decision either -- it is a property of the transport, so this is the layer that can read it.
     */
    post: operations['log_in_api_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Who the presented session token identifies
     * @description Answer the identity the token carries, without reading anything (RF-07).
     *
     *     This is what a reloaded page calls to find out whether the token it kept is still good, so it
     *     runs once per navigation and has to stay cheap: the claims were already verified by
     *     `get_current_user`, and looking `users` up again would add a round trip to confirm something
     *     the signature already confirmed. A row that changed underneath is not a risk worth a query --
     *     the token expires in an hour either way (ADR-004).
     *
     *     It takes no parameter, and that is the whole of Article III here: there is no id to pass, so
     *     there is none to substitute.
     */
    get: operations['read_current_user_api_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/favorites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The favourite stocks of whoever is asking
     * @description Answer the grid of the token's user, empty list included (RF-01, RF-07).
     *
     *     The identity comes from `get_current_user` and from nowhere else: this route takes no id, so
     *     there is none to substitute (Article III). An empty list is a result and not a 404 -- the
     *     text the screen writes in place of the rows is its business, not this one's.
     */
    get: operations['read_favorites_api_favorites_get'];
    put?: never;
    /**
     * Add a stock to the favourites of whoever is asking
     * @description Answer 201 when the favourite was created and 200 when it already was there (RF-18).
     *
     *     Never a 409: adding the same action twice is not an error, it is an operation that was
     *     already done -- and TEST-04 asks for exactly that, no duplicate **and** no failure. The
     *     difference travels in the status because the protocol already has it; a field in the body
     *     saying the same thing would be a second source of truth.
     *
     *     The 200 is written onto the `Response` rather than declared, because a route has one
     *     `status_code` and this one has two answers. It is the same mechanism `/api/health` uses.
     *
     *     The symbol is the object and the identity is the token: `user_id` is not a parameter of this
     *     route, so there is none to substitute (Article III).
     */
    post: operations['add_to_favorites_api_favorites_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/favorites/{symbol}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove a stock from the favourites of whoever is asking
     * @description Answer 204, and answer it whether or not the favourite was there (RF-24).
     *
     *     The symbol travels in the path and **that is not an identity**: it is the object. What scopes
     *     it to the list of whoever is asking is the `WHERE user_id = <the token's>` of the repository,
     *     which is also why RF-28 holds without a single extra check (Article III).
     *
     *     Validated with the same pattern as the add, because it is the same value seen twice: what
     *     cannot be a segment of a path was never a symbol.
     */
    delete: operations['remove_from_favorites_api_favorites__symbol__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/stocks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Catalogue suggestions for what somebody is typing
     * @description Answer at most twenty suggestions, most relevant first (RF-08 to RF-13).
     *
     *     The text travels to the service exactly as it arrived: normalising is a decision, and
     *     decisions are not made at this layer (PY-06). The minimum length is declared in both places
     *     on purpose and the two are not symmetric -- this one measures what was received, and answers
     *     422; the service measures what was asked once stripped, and answers `200 []`.
     *
     *     `MIN_QUERY_LENGTH` is imported from the service rather than written again, so RF-13 cannot
     *     end up as two literals that one day say different numbers. The maximum is API4 in one line.
     *
     *     Protected, like every route of this API: the catalogue is not user data, but a search box
     *     left open is the ingestion's work handed out for free.
     */
    get: operations['search_the_catalogue_api_stocks_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/quotes/{symbol}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The series a chart of that stock is drawn from
     * @description Answer the series of that symbol, and the state it is served in (RF-13, RF-16).
     *
     *     One route for the two modes of the screen, because they are not two questions: without
     *     `from` and `to` it is today's session in market hours, and with them it is the window the
     *     person asked for. Which hours those are is decided in the service -- this layer carries the
     *     two instants exactly as they were written, naive, and puts no timezone on them.
     *
     *     The symbol travels in the path and **that is not an identity**: it is the object. Who is
     *     asking comes from the token and from nowhere else (Article III), and a symbol that is not on
     *     that person's list is a 404 that never reaches the provider (RF-35).
     *
     *     The provider arrives by dependency rather than being built here: it is what lets the suite
     *     exercise this endpoint with no network and no API key (TEST-03).
     */
    get: operations['read_quotes_api_quotes__symbol__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Process and dependency status
     * @description Answer 200 when the database replies, and 503 when it does not.
     *
     *     The 503 matters as much as the 200: answering 200 with the database down would keep the
     *     proxy sending traffic to an instance that can serve nothing.
     */
    get: operations['health_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AddFavoriteRequest
     * @description The symbol somebody asks to follow.
     *
     *     `extra="forbid"` is API3:2023 (BOPLA): a body carrying fields nobody declared is a body that
     *     will eventually carry one somebody forgot to ignore -- a `user_id`, for instance, which is
     *     exactly what Article III says never arrives from the request.
     *
     *     The pattern is the one of a symbol and not a general string: what cannot be a segment of a
     *     path cannot be a symbol, because this same value travels in the URL of the delete.
     */
    AddFavoriteRequest: {
      /** Symbol */
      symbol: string;
    };
    /**
     * CurrentUserResponse
     * @description Who the presented token says is calling (RF-07).
     *
     *     Two fields, and the reason there are only two is worth stating: this answers a token, not a
     *     row. Adding `username` -- or anything else `users` happens to hold -- would turn a claim the
     *     caller already carries into a read of their record, and API3:2023 (BOPLA) is exactly the habit
     *     of answering the whole row because it was already loaded. Nothing here is loaded.
     */
    CurrentUserResponse: {
      /** Id */
      id: number;
      /** Full Name */
      full_name: string;
    };
    /**
     * FavoriteItem
     * @description One row of `Mis Acciones`, as the grid reads it (RF-03).
     *
     *     Three fields, and the reason there are only three is worth stating: the screen draws a
     *     symbol, a name and a currency, and anything else the tables happen to hold -- when it was
     *     added, which market it trades in -- would be answered for no reason. That habit is
     *     API3:2023 (BOPLA).
     */
    FavoriteItem: {
      /** Symbol */
      symbol: string;
      /** Name */
      name: string;
      /** Currency */
      currency: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HealthStatus
     * @description What health answers.
     *
     *     Three fields, and none of them derived from configuration: no DSN, no host, no database
     *     name. A health endpoint that explains how it connects is a map for whoever reads it
     *     (Article I).
     */
    HealthStatus: {
      /** Status */
      status: string;
      /** Database */
      database: string;
      /** Version */
      version: string;
    };
    /**
     * LoginRequest
     * @description The credential a caller presents.
     *
     *     `extra="forbid"` is API3:2023 (BOPLA): a body that carries fields nobody declared is a body
     *     that will eventually carry one somebody forgot to ignore.
     *
     *     The maximum lengths are API4 in one line -- a password of a megabyte must not reach Argon2,
     *     which is deliberately expensive -- and they are refused by the schema, before the route runs.
     */
    LoginRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /**
     * LoginResponse
     * @description The session a good credential buys.
     *
     *     `full_name` travels here so the header can be painted without a second request (RF-08,
     *     ADR-004); it is the same value as the token's `name` claim, not a second source of truth. And
     *     `expires_in` is derived from `ACCESS_TOKEN_TTL`, so the frontend holds no copy of the number.
     */
    LoginResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       * @constant
       */
      token_type: 'bearer';
      /** Expires In */
      expires_in: number;
      /** Full Name */
      full_name: string;
    };
    /**
     * QuoteInterval
     * @description The three intervals REQ-16 offers the user, and the only ones the table accepts.
     * @enum {string}
     */
    QuoteInterval: '1min' | '5min' | '15min';
    /**
     * QuotePointOut
     * @description One point of the chart: the instant, and the close of that candle.
     *
     *     The price crosses the wire as a string, which is what Pydantic does with a `Decimal` and is
     *     kept on purpose: it travels with the decimals the provider sent and becomes a `number` once,
     *     at the edge of the chart, which is the one place a number is needed at all.
     */
    QuotePointOut: {
      /**
       * Ts
       * Format: date-time
       */
      ts: string;
      /** Price */
      price: string;
    };
    /**
     * QuoteSeriesResponse
     * @description The series and what has to be said about it (ERR-05).
     *
     *     The four states answer 200, every one of them: a spent quota is not a failure of the caller,
     *     and a closed market is the normal state of two days out of seven. And no field names the
     *     provider, neither in the happy path nor in the three notices (RF-26, Article I).
     */
    QuoteSeriesResponse: {
      /** Symbol */
      symbol: string;
      /** Interval */
      interval: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'stale' | 'market_closed' | 'no_data';
      /** Session Date */
      session_date: string | null;
      /** Points */
      points: components['schemas']['QuotePointOut'][];
    };
    /**
     * StockSuggestion
     * @description One line of the dropdown of the `Símbolo` field (RF-08, RF-09).
     *
     *     Three fields and not the four of `StockInfo`: `is_listed` is always true on this route --
     *     the search excludes what stopped trading (RF-12) -- and a constant in a contract is a field
     *     the frontend has to type for no reason.
     */
    StockSuggestion: {
      /** Symbol */
      symbol: string;
      /** Name */
      name: string;
      /** Currency */
      currency: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  log_in_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_current_user_api_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurrentUserResponse'];
        };
      };
    };
  };
  read_favorites_api_favorites_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FavoriteItem'][];
        };
      };
    };
  };
  add_to_favorites_api_favorites_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddFavoriteRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FavoriteItem'];
        };
      };
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FavoriteItem'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_from_favorites_api_favorites__symbol__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        symbol: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  search_the_catalogue_api_stocks_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StockSuggestion'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_quotes_api_quotes__symbol__get: {
    parameters: {
      query: {
        interval: components['schemas']['QuoteInterval'];
        from?: string | null;
        to?: string | null;
      };
      header?: never;
      path: {
        symbol: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['QuoteSeriesResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
    };
  };
}
