/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Exchange a username and a password for a session token
     * @description Answer a session token, or let the service's refusal become a 401 or a 429.
     *
     *     The username and the password travel to the service exactly as they arrived: normalising them
     *     is a decision, and decisions are not made here. The address is the exception, and it is not a
     *     decision either -- it is a property of the transport, so this is the layer that can read it.
     */
    post: operations['log_in_api_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Who the presented session token identifies
     * @description Answer the identity the token carries, without reading anything (RF-07).
     *
     *     This is what a reloaded page calls to find out whether the token it kept is still good, so it
     *     runs once per navigation and has to stay cheap: the claims were already verified by
     *     `get_current_user`, and looking `users` up again would add a round trip to confirm something
     *     the signature already confirmed. A row that changed underneath is not a risk worth a query --
     *     the token expires in an hour either way (ADR-004).
     *
     *     It takes no parameter, and that is the whole of Article III here: there is no id to pass, so
     *     there is none to substitute.
     */
    get: operations['read_current_user_api_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Process and dependency status
     * @description Answer 200 when the database replies, and 503 when it does not.
     *
     *     The 503 matters as much as the 200: answering 200 with the database down would keep the
     *     proxy sending traffic to an instance that can serve nothing.
     */
    get: operations['health_api_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CurrentUserResponse
     * @description Who the presented token says is calling (RF-07).
     *
     *     Two fields, and the reason there are only two is worth stating: this answers a token, not a
     *     row. Adding `username` -- or anything else `users` happens to hold -- would turn a claim the
     *     caller already carries into a read of their record, and API3:2023 (BOPLA) is exactly the habit
     *     of answering the whole row because it was already loaded. Nothing here is loaded.
     */
    CurrentUserResponse: {
      /** Id */
      id: number;
      /** Full Name */
      full_name: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * HealthStatus
     * @description What health answers.
     *
     *     Three fields, and none of them derived from configuration: no DSN, no host, no database
     *     name. A health endpoint that explains how it connects is a map for whoever reads it
     *     (Article I).
     */
    HealthStatus: {
      /** Status */
      status: string;
      /** Database */
      database: string;
      /** Version */
      version: string;
    };
    /**
     * LoginRequest
     * @description The credential a caller presents.
     *
     *     `extra="forbid"` is API3:2023 (BOPLA): a body that carries fields nobody declared is a body
     *     that will eventually carry one somebody forgot to ignore.
     *
     *     The maximum lengths are API4 in one line -- a password of a megabyte must not reach Argon2,
     *     which is deliberately expensive -- and they are refused by the schema, before the route runs.
     */
    LoginRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /**
     * LoginResponse
     * @description The session a good credential buys.
     *
     *     `full_name` travels here so the header can be painted without a second request (RF-08,
     *     ADR-004); it is the same value as the token's `name` claim, not a second source of truth. And
     *     `expires_in` is derived from `ACCESS_TOKEN_TTL`, so the frontend holds no copy of the number.
     */
    LoginResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       * @constant
       */
      token_type: 'bearer';
      /** Expires In */
      expires_in: number;
      /** Full Name */
      full_name: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  log_in_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_current_user_api_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurrentUserResponse'];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
    };
  };
}
