"""The migration of the autocomplete, run against a real database (DB-01, DB-03).

`529bd7f366dd` creates `pg_trgm` and the two GIN indexes the search reads through, and it is the
one kind of code that no other test can reach: the suite runs against a database somebody already
migrated, so the tables being there says nothing about the file that put them there.

Three claims, and the second is the one that is easy to get wrong:

- **`upgrade` creates the two indexes, with trigram operator classes.** A GIN index over a plain
  `text_ops` would be accepted by Postgres and useless for an `ILIKE`, so the operator class is
  part of the assertion and not decoration.
- **`downgrade` drops the indexes and leaves the extension.** The asymmetry is deliberate: an
  extension is database-wide and may have other users, so dropping it would be an effect nobody
  asked for. A test that demanded symmetry would be asking for that damage.
- **Running the cycle twice works.** The second `upgrade` meets an extension that is already
  there, which is exactly what `CREATE EXTENSION IF NOT EXISTS` exists for -- and what a managed
  Postgres, where the operator creates the extension by hand, looks like on every deploy.

And `alembic check`, which is DB-01 itself: the models and the tables describe the same schema.
CI runs it as a step; having it here as well is what makes a drifted model fail in the suite the
developer runs, and not only after the push.

These tests are **synchronous on purpose**. Alembic's `env.py` calls `asyncio.run` itself, so
driving it from an async test would try to start a loop inside a running one. The database is
read with `asyncio.run` from the same sync body, which is the only place in the suite where that
is the right shape.

They also do real DDL outside the rolled-back transaction of `conftest.py`, which is unavoidable:
a migration that could be rolled back by the test harness would not be a migration. The fixture
leaves the database at `head` whatever happens, so the files that run after this one find the
schema they expect.
"""

import asyncio
from collections.abc import Iterator
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

from app.settings import get_settings

_BACKEND_ROOT = Path(__file__).resolve().parents[2]

# The revision this one is built on: downgrading to it is what removes the indexes without
# touching anything else of the schema.
_BEFORE = "394dab64d255"

_INDEXES = {"ix_stocks_symbol_trgm", "ix_stocks_name_trgm"}


def _alembic() -> Config:
    """The configuration the CLI would build, with the URL coming from Settings as ever."""
    config = Config(str(_BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(_BACKEND_ROOT / "alembic"))

    return config


async def _read(statement: str) -> list[tuple[object, ...]]:
    """Run one read against the real database and hand back its rows."""
    engine = create_async_engine(get_settings().database_url)
    try:
        async with engine.connect() as connection:
            result = await connection.execute(text(statement))

            return [tuple(row) for row in result]
    finally:
        await engine.dispose()


def _indexes_of_stocks() -> dict[str, str]:
    """Every index on `stocks`, by name, with the definition Postgres reflects back."""
    rows = asyncio.run(
        _read("SELECT indexname, indexdef FROM pg_indexes WHERE tablename = 'stocks'")
    )

    return {str(name): str(definition) for name, definition in rows}


def _trigram_extension_is_installed() -> bool:
    """Whether `pg_trgm` is present in this database."""
    return bool(asyncio.run(_read("SELECT 1 FROM pg_extension WHERE extname = 'pg_trgm'")))


@pytest.fixture
def at_head() -> Iterator[Config]:
    """Hand over the Alembic config, and leave the database migrated whatever the test did."""
    config = _alembic()

    yield config

    command.upgrade(config, "head")


class TestTheUpgrade:
    """What the migration creates, read back from the catalogue of Postgres."""

    def test_the_two_indexes_exist_after_it(self, at_head: Config) -> None:
        """Against a schema that does not have them yet: down first, then up."""
        command.downgrade(at_head, _BEFORE)
        command.upgrade(at_head, "head")

        assert _INDEXES <= set(_indexes_of_stocks())

    def test_they_are_gin_indexes_over_trigram_operator_classes(self, at_head: Config) -> None:
        """A GIN index with the default operator class would be accepted and useless."""
        command.downgrade(at_head, _BEFORE)
        command.upgrade(at_head, "head")

        definitions = _indexes_of_stocks()

        assert all("USING gin" in definitions[name] for name in _INDEXES)
        assert all("gin_trgm_ops" in definitions[name] for name in _INDEXES)

    def test_the_extension_is_installed(self, at_head: Config) -> None:
        """The operator classes above do not exist without it, so it comes first."""
        command.downgrade(at_head, _BEFORE)
        command.upgrade(at_head, "head")

        assert _trigram_extension_is_installed()


class TestTheDowngrade:
    """What it undoes, and the one thing it deliberately does not."""

    def test_the_two_indexes_are_gone(self, at_head: Config) -> None:
        """Down means down: nothing of this revision is left on the table."""
        command.downgrade(at_head, _BEFORE)

        assert _INDEXES.isdisjoint(_indexes_of_stocks())

    def test_the_primary_key_index_is_untouched(self, at_head: Config) -> None:
        """It drops what it created and not what it found: `stocks` keeps its key."""
        command.downgrade(at_head, _BEFORE)

        assert _indexes_of_stocks() != {}

    def test_the_extension_survives_it(self, at_head: Config) -> None:
        """Asymmetric on purpose: an extension can have users this migration never met."""
        command.downgrade(at_head, _BEFORE)

        assert _trigram_extension_is_installed()


class TestRunningItTwice:
    """The second time around, the extension is already there -- and that is the normal case."""

    def test_two_full_cycles_do_not_fail(self, at_head: Config) -> None:
        """`CREATE EXTENSION IF NOT EXISTS` is what makes the second upgrade a no-op."""
        for _ in range(2):
            command.downgrade(at_head, _BEFORE)
            command.upgrade(at_head, "head")

        assert _INDEXES <= set(_indexes_of_stocks())
        assert _trigram_extension_is_installed()


class TestTheModelsMatchTheTables:
    """DB-01: `alembic check`, run from the suite and not only from CI."""

    def test_alembic_check_finds_no_drift(self, at_head: Config) -> None:
        """The two `Index(...)` at the foot of `stocks/models.py` describe what was migrated.

        This is the assertion the migration of task 7 had to satisfy before anything else could
        be written on top of it: an operator class the reflection reads differently shows up
        here as a diff, and a schema that drifts is a schema nobody can autogenerate against
        again.
        """
        command.upgrade(at_head, "head")

        try:
            command.check(at_head)
        except AutogenerateDiffsDetected as drift:  # pragma: no cover - the failure message
            pytest.fail(f"alembic check found drift: {drift}")
